title: "The Pool Industry Report"
description: "Your go-to source for pool industry news, insights, and trends."
baseurl: "" # Leave this blank unless your site is in a subdirectory
url: "http://localhost:4000" # Change this to your actual domain when live
